### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samdruster** [ericglau/defi-ls#25]
- Issue Type: `Bug`
- Extension Name: `defi-ls`
- Extension Version: `0.0.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ericglau** [comment]
Closing since there is no information here.  Please reopen with more details if the issue still occurs.
